// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectsem3_backend.data;

#nullable disable

namespace projectsem3_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240118063139_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectsem3_backend.Models.AdminLoginMst", b =>
                {
                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserName");

                    b.ToTable("AdminLoginMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Property<string>("Brand_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Brand_ID");

                    b.ToTable("BrandMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Style_Code")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Style_Code");

                    b.HasIndex("UserID");

                    b.ToTable("CartLists");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Property<string>("Cat_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Cat_ID");

                    b.ToTable("CatMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Property<string>("Certify_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Certify_ID");

                    b.ToTable("CertifyMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Property<string>("DimID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimCrt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimImg")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimPrice")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimSubType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimID");

                    b.ToTable("DimInfoMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimSubType_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Dim_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Dim_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Dim_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Dim_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Dim_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Dim_Size")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Style_Code", "DimQlty_ID");

                    b.HasIndex("DimID")
                        .IsUnique();

                    b.HasIndex("DimQlty_ID");

                    b.HasIndex("DimSubType_ID");

                    b.ToTable("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimQlty_ID");

                    b.ToTable("DimQltyMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Property<string>("DimSubType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimSubType_ID");

                    b.ToTable("DimQltySubMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Property<string>("GoldType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gold_Crt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("GoldType_ID");

                    b.ToTable("GoldKrtMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("Cdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Inquiries");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoldType_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gold_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Gold_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Gold_Rate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Gold_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jewellery_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Net_Gold")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Other_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int>("Pairs")
                        .HasColumnType("int");

                    b.Property<string>("Prod_ID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prod_Quality")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Stone_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Stone_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Tot_Gross_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Tot_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<decimal>("Wstg")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Wstg_Per")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Style_Code");

                    b.HasIndex("Brand_ID");

                    b.HasIndex("Cat_ID");

                    b.HasIndex("Certify_ID");

                    b.HasIndex("GoldType_ID");

                    b.HasIndex("Jewellery_ID");

                    b.HasIndex("Prod_ID");

                    b.ToTable("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jewellery_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.ToTable("JewelTypeMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("Gold_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Making_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<decimal>("Stone_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal>("Total_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Order_ID", "Style_Code");

                    b.HasIndex("Style_Code");

                    b.ToTable("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("Order_Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Note")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UserID")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Order_ID");

                    b.HasIndex("UserID");

                    b.ToTable("OrderMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Property<string>("Prod_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prod_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Prod_ID");

                    b.ToTable("ProdMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Stone_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stone_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stone_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stone_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal>("Stone_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Style_Code", "StoneQlty_ID");

                    b.HasIndex("StoneQlty_ID");

                    b.ToTable("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoneQlty")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("StoneQlty_ID");

                    b.ToTable("StoneQltyMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CDate")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DOB")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MobNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserRegMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("CartLists")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("CartLists")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMst");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.DimInfoMst", "DimInfoMst")
                        .WithOne("DimMst")
                        .HasForeignKey("projectsem3_backend.Models.DimMst", "DimID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.DimQltyMst", "DimQltyMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimQlty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.DimQltySubMst", "DimQltySubMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimSubType_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimInfoMst");

                    b.Navigation("DimQltyMst");

                    b.Navigation("DimQltySubMst");

                    b.Navigation("ItemMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("Inquiries")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.BrandMst", "BrandMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Brand_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.CatMst", "CatMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Cat_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.CertifyMst", "CertifyMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Certify_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.GoldKrtMst", "GoldKrtMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("GoldType_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.JewelTypeMst", "JewelTypeMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Jewellery_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ProdMst", "ProdMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Prod_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("BrandMst");

                    b.Navigation("CatMst");

                    b.Navigation("CertifyMst");

                    b.Navigation("GoldKrtMst");

                    b.Navigation("JewelTypeMst");

                    b.Navigation("ProdMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.OrderMst", "OrderMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMst");

                    b.Navigation("OrderMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("OrderMsts")
                        .HasForeignKey("UserID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.StoneQltyMst", "StoneQltyMst")
                        .WithMany("StoneMsts")
                        .HasForeignKey("StoneQlty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("StoneMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMst");

                    b.Navigation("StoneQltyMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Navigation("DimMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("DimMsts");

                    b.Navigation("OrderDetailMsts");

                    b.Navigation("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Navigation("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Navigation("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("Inquiries");

                    b.Navigation("OrderMsts");
                });
#pragma warning restore 612, 618
        }
    }
}
