// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectsem3_backend.data;

#nullable disable

namespace projectsem3_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240217154941_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectsem3_backend.Models.AdminLoginMst", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserName");

                    b.ToTable("AdminLoginMsts");

                    b.HasData(
                        new
                        {
                            UserName = "admin1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(2212),
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(2227)
                        },
                        new
                        {
                            UserName = "admin2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(2230),
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(2231)
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Property<string>("Brand_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Brand_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Brand_ID");

                    b.ToTable("BrandMsts");

                    b.HasData(
                        new
                        {
                            Brand_ID = "1",
                            Brand_Type = "Asmi",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(3990),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(4000),
                            Visible = true
                        },
                        new
                        {
                            Brand_ID = "2",
                            Brand_Type = "D’damas",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(4006),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(4007),
                            Visible = true
                        },
                        new
                        {
                            Brand_ID = "3",
                            Brand_Type = "ABC Jewelers",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(4009),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(4010),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Style_Code");

                    b.HasIndex("UserID");

                    b.ToTable("CartLists");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            MRP = 1000m,
                            Product_Name = "Product 1",
                            Quantity = 1,
                            Style_Code = "1",
                            UserID = "1"
                        },
                        new
                        {
                            ID = "2",
                            MRP = 2000m,
                            Product_Name = "Product 2",
                            Quantity = 1,
                            Style_Code = "2",
                            UserID = "2"
                        },
                        new
                        {
                            ID = "3",
                            MRP = 1500m,
                            Product_Name = "Product 3",
                            Quantity = 1,
                            Style_Code = "3",
                            UserID = "3"
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Property<string>("Cat_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Cat_ID");

                    b.ToTable("CatMsts");

                    b.HasData(
                        new
                        {
                            Cat_ID = "1",
                            Cat_Name = "Silver Jewelry",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5037),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5039),
                            Visible = true
                        },
                        new
                        {
                            Cat_ID = "2",
                            Cat_Name = "Gold Jewelry",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5042),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5043),
                            Visible = true
                        },
                        new
                        {
                            Cat_ID = "3",
                            Cat_Name = "Diamond Jewelry",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5044),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(5045),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Property<string>("Certify_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Certify_ID");

                    b.ToTable("CertifyMsts");

                    b.HasData(
                        new
                        {
                            Certify_ID = "1",
                            Certify_Type = "BIS Hallmark",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9676),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9680),
                            Visible = true
                        },
                        new
                        {
                            Certify_ID = "2",
                            Certify_Type = "IGI",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9682),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9683),
                            Visible = true
                        },
                        new
                        {
                            Certify_ID = "3",
                            Certify_Type = "GIA",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9684),
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 183, DateTimeKind.Local).AddTicks(9685),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Property<string>("DimID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimCrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DimYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimID");

                    b.ToTable("DimInfoMsts");

                    b.HasData(
                        new
                        {
                            DimID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5609),
                            DimCrt = "1",
                            DimImg = "",
                            DimPrice = "1000",
                            DimSubType = "Premium",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5615),
                            Visible = true
                        },
                        new
                        {
                            DimID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5620),
                            DimCrt = "2",
                            DimImg = "",
                            DimPrice = "2000",
                            DimSubType = "Standard",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5621),
                            Visible = true
                        },
                        new
                        {
                            DimID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5624),
                            DimCrt = "3",
                            DimImg = "",
                            DimPrice = "1500",
                            DimSubType = "Economy",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 182, DateTimeKind.Local).AddTicks(5625),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimSubType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Dim_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Size")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Style_Code", "DimQlty_ID");

                    b.HasIndex("DimID")
                        .IsUnique()
                        .HasFilter("[DimID] IS NOT NULL");

                    b.HasIndex("DimQlty_ID");

                    b.HasIndex("DimSubType_ID");

                    b.ToTable("DimMsts");

                    b.HasData(
                        new
                        {
                            Style_Code = "1",
                            DimQlty_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5823),
                            DimID = "1",
                            DimSubType_ID = "1",
                            Dim_Amt = 1000m,
                            Dim_Crt = 1m,
                            Dim_Gm = 1m,
                            Dim_Pcs = 1m,
                            Dim_Rate = 1000m,
                            Dim_Size = 1m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5841)
                        },
                        new
                        {
                            Style_Code = "2",
                            DimQlty_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5848),
                            DimID = "2",
                            DimSubType_ID = "2",
                            Dim_Amt = 2000m,
                            Dim_Crt = 2m,
                            Dim_Gm = 2m,
                            Dim_Pcs = 2m,
                            Dim_Rate = 2000m,
                            Dim_Size = 2m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5849)
                        },
                        new
                        {
                            Style_Code = "3",
                            DimQlty_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5854),
                            DimID = "3",
                            DimSubType_ID = "3",
                            Dim_Amt = 1500m,
                            Dim_Crt = 3m,
                            Dim_Gm = 3m,
                            Dim_Pcs = 3m,
                            Dim_Rate = 1500m,
                            Dim_Size = 3m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 178, DateTimeKind.Local).AddTicks(5855)
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimQlty_ID");

                    b.ToTable("DimQltyMsts");

                    b.HasData(
                        new
                        {
                            DimQlty_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(200),
                            DimQlty = "AD",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(206),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(209),
                            DimQlty = "VS",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(210),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(213),
                            DimQlty = "SI",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(214),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(216),
                            DimQlty = "FD",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(217),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "5",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(219),
                            DimQlty = "WS",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 179, DateTimeKind.Local).AddTicks(220),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Property<string>("DimSubType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimSubType_ID");

                    b.ToTable("DimQltySubMsts");

                    b.HasData(
                        new
                        {
                            DimSubType_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(530),
                            DimQlty = "Premium",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(536),
                            Visible = true
                        },
                        new
                        {
                            DimSubType_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(539),
                            DimQlty = "Standard",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(541),
                            Visible = true
                        },
                        new
                        {
                            DimSubType_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(543),
                            DimQlty = "Economy",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 180, DateTimeKind.Local).AddTicks(544),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Property<string>("GoldType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gold_Crt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gold_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("GoldType_ID");

                    b.ToTable("GoldKrtMsts");

                    b.HasData(
                        new
                        {
                            GoldType_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4406),
                            Gold_Crt = "18K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4410),
                            Visible = true
                        },
                        new
                        {
                            GoldType_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4413),
                            Gold_Crt = "22K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4413),
                            Visible = true
                        },
                        new
                        {
                            GoldType_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4415),
                            Gold_Crt = "24K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(4416),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Cdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Inquiries");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            Cdate = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(8074),
                            City = "HCM",
                            Comment = "Test 1",
                            Contact = "0123456789",
                            EmailID = "user1@gmail.com",
                            Name = "User 1",
                            UserID = "1",
                            Visible = true
                        },
                        new
                        {
                            ID = "2",
                            Cdate = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(8084),
                            City = "HCM",
                            Comment = "Test 2",
                            Contact = "0987654321",
                            EmailID = "user2@gmail.com",
                            Name = "User 2",
                            UserID = "2",
                            Visible = true
                        },
                        new
                        {
                            ID = "3",
                            Cdate = new DateTime(2024, 2, 17, 22, 49, 41, 153, DateTimeKind.Local).AddTicks(8087),
                            City = "HCM",
                            Comment = "Test 3",
                            Contact = "0135792468",
                            EmailID = "user3@gmail.com",
                            Name = "User 3",
                            UserID = "3",
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoldType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Gold_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Rate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jewellery_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Net_Gold")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Other_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Pairs")
                        .HasColumnType("int");

                    b.Property<string>("Prod_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prod_Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Stone_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Stone_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Tot_Gross_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Tot_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Wstg")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Wstg_Per")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Style_Code");

                    b.HasIndex("Brand_ID");

                    b.HasIndex("Cat_ID");

                    b.HasIndex("Certify_ID");

                    b.HasIndex("GoldType_ID");

                    b.HasIndex("Jewellery_ID");

                    b.HasIndex("Prod_ID");

                    b.HasIndex("StoneQlty_ID");

                    b.ToTable("ItemMsts");

                    b.HasData(
                        new
                        {
                            Style_Code = "1",
                            Brand_ID = "1",
                            Cat_ID = "1",
                            Certify_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7293),
                            GoldType_ID = "1",
                            Gold_Amt = 1000m,
                            Gold_Making = 1000m,
                            Gold_Rate = 1000m,
                            Gold_Wt = 1m,
                            ImagePath = "https://sjc.com.vn/upload/35-nutg0004_1475050374.jpg",
                            Jewellery_ID = "1",
                            MRP = 1000m,
                            Net_Gold = 1m,
                            Other_Making = 1000m,
                            Pairs = 1,
                            Prod_ID = "1",
                            Prod_Quality = "Premium",
                            Product_Name = "Product 1",
                            Quantity = 100,
                            StoneQlty_ID = "1",
                            Stone_Making = 1000m,
                            Stone_Wt = 1m,
                            Tot_Gross_Wt = 1m,
                            Tot_Making = 1000m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7320),
                            Visible = true,
                            Wstg = 1m,
                            Wstg_Per = 1m
                        },
                        new
                        {
                            Style_Code = "2",
                            Brand_ID = "2",
                            Cat_ID = "2",
                            Certify_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7359),
                            GoldType_ID = "2",
                            Gold_Amt = 2000m,
                            Gold_Making = 2000m,
                            Gold_Rate = 2000m,
                            Gold_Wt = 2m,
                            ImagePath = "https://sjc.com.vn/upload/28-ltdc0096_1475054675.jpg",
                            Jewellery_ID = "2",
                            MRP = 2000m,
                            Net_Gold = 2m,
                            Other_Making = 2000m,
                            Pairs = 2,
                            Prod_ID = "2",
                            Prod_Quality = "Standard",
                            Product_Name = "Product 2",
                            Quantity = 100,
                            StoneQlty_ID = "2",
                            Stone_Making = 2000m,
                            Stone_Wt = 2m,
                            Tot_Gross_Wt = 2m,
                            Tot_Making = 2000m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7361),
                            Visible = true,
                            Wstg = 2m,
                            Wstg_Per = 2m
                        },
                        new
                        {
                            Style_Code = "3",
                            Brand_ID = "3",
                            Cat_ID = "3",
                            Certify_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7374),
                            GoldType_ID = "3",
                            Gold_Amt = 1500m,
                            Gold_Making = 1500m,
                            Gold_Rate = 1500m,
                            Gold_Wt = 3m,
                            ImagePath = "",
                            Jewellery_ID = "3",
                            MRP = 1500m,
                            Net_Gold = 3m,
                            Other_Making = 1500m,
                            Pairs = 3,
                            Prod_ID = "3",
                            Prod_Quality = "Economy",
                            Product_Name = "Product 3",
                            Quantity = 100,
                            StoneQlty_ID = "3",
                            Stone_Making = 1500m,
                            Stone_Wt = 3m,
                            Tot_Gross_Wt = 3m,
                            Tot_Making = 1500m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 172, DateTimeKind.Local).AddTicks(7376),
                            Visible = true,
                            Wstg = 3m,
                            Wstg_Per = 3m
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Property<string>("Jewellery_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jewellery_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Jewellery_ID");

                    b.ToTable("JewelTypeMsts");

                    b.HasData(
                        new
                        {
                            Jewellery_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9328),
                            Jewellery_Type = "Ring",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9331),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9333),
                            Jewellery_Type = "Earring",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9333),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9335),
                            Jewellery_Type = "Necklace",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9336),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9337),
                            Jewellery_Type = "Bracelet",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(9338),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_ID", "Style_Code");

                    b.HasIndex("Style_Code");

                    b.ToTable("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("Order_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("cancelreason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cvv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("orderPayment")
                        .HasColumnType("int");

                    b.Property<string>("order_MobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymenturl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Order_ID");

                    b.HasIndex("UserID");

                    b.ToTable("OrderMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Property<string>("Prod_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prod_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Prod_ID");

                    b.ToTable("ProdMsts");

                    b.HasData(
                        new
                        {
                            Prod_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8765),
                            Prod_Type = "Gold Ring",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8769),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8774),
                            Prod_Type = "Diamond Earring",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8775),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8776),
                            Prod_Type = "Silver Necklace",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8777),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8778),
                            Prod_Type = "Silver Ring",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 184, DateTimeKind.Local).AddTicks(8779),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.Property<string>("Stone_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemMstStyle_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Stone_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Stone_ID");

                    b.HasIndex("ItemMstStyle_Code");

                    b.HasIndex("StoneQlty_ID");

                    b.ToTable("StoneMsts");

                    b.HasData(
                        new
                        {
                            Stone_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1089),
                            StoneQlty_ID = "1",
                            Stone_Amt = 1000m,
                            Stone_Crt = 1m,
                            Stone_Gm = 1m,
                            Stone_Pcs = 1m,
                            Stone_Rate = 1000m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1106)
                        },
                        new
                        {
                            Stone_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1116),
                            StoneQlty_ID = "2",
                            Stone_Amt = 2000m,
                            Stone_Crt = 2m,
                            Stone_Gm = 2m,
                            Stone_Pcs = 2m,
                            Stone_Rate = 2000m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1116)
                        },
                        new
                        {
                            Stone_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1119),
                            StoneQlty_ID = "3",
                            Stone_Amt = 1500m,
                            Stone_Crt = 3m,
                            Stone_Gm = 3m,
                            Stone_Pcs = 3m,
                            Stone_Rate = 1500m,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 160, DateTimeKind.Local).AddTicks(1120)
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoneQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stone_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("StoneQlty_ID");

                    b.ToTable("StoneQltyMsts");

                    b.HasData(
                        new
                        {
                            StoneQlty_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4312),
                            StoneQlty = "Ruby",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4326),
                            Visible = true
                        },
                        new
                        {
                            StoneQlty_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4328),
                            StoneQlty = "Meena",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4329),
                            Visible = true
                        },
                        new
                        {
                            StoneQlty_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4331),
                            StoneQlty = "Sapphire",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 161, DateTimeKind.Local).AddTicks(4332),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Activate")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<string>("MobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserRegMsts");

                    b.HasData(
                        new
                        {
                            UserID = "1",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(69),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(72),
                            DOB = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(63),
                            EmailID = "user1@gmail.com",
                            IsVerified = true,
                            MobNo = "0123456789",
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(73),
                            UserFname = "User",
                            UserLname = "1",
                            UserName = "user1"
                        },
                        new
                        {
                            UserID = "2",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(77),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(79),
                            DOB = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(76),
                            EmailID = "user2@gmail.com",
                            IsVerified = true,
                            MobNo = "0123456789",
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(80),
                            UserFname = "User",
                            UserLname = "2",
                            UserName = "user2"
                        },
                        new
                        {
                            UserID = "3",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(83),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(85),
                            DOB = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(82),
                            EmailID = "user3@gmail.com",
                            IsVerified = true,
                            MobNo = "0123456789",
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 17, 22, 49, 41, 155, DateTimeKind.Local).AddTicks(86),
                            UserFname = "User",
                            UserLname = "3",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("CartLists")
                        .HasForeignKey("Style_Code");

                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("CartLists")
                        .HasForeignKey("UserID");

                    b.Navigation("ItemMst");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.DimInfoMst", "DimInfoMst")
                        .WithOne("DimMst")
                        .HasForeignKey("projectsem3_backend.Models.DimMst", "DimID");

                    b.HasOne("projectsem3_backend.Models.DimQltyMst", "DimQltyMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimQlty_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.DimQltySubMst", "DimQltySubMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimSubType_ID");

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DimInfoMst");

                    b.Navigation("DimQltyMst");

                    b.Navigation("DimQltySubMst");

                    b.Navigation("ItemMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("Inquiries")
                        .HasForeignKey("UserID");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.BrandMst", "BrandMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Brand_ID");

                    b.HasOne("projectsem3_backend.Models.CatMst", "CatMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Cat_ID");

                    b.HasOne("projectsem3_backend.Models.CertifyMst", "CertifyMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Certify_ID");

                    b.HasOne("projectsem3_backend.Models.GoldKrtMst", "GoldKrtMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("GoldType_ID");

                    b.HasOne("projectsem3_backend.Models.JewelTypeMst", "JewelTypeMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Jewellery_ID");

                    b.HasOne("projectsem3_backend.Models.ProdMst", "ProdMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Prod_ID");

                    b.HasOne("projectsem3_backend.Models.StoneQltyMst", "StoneQltyMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("StoneQlty_ID");

                    b.Navigation("BrandMst");

                    b.Navigation("CatMst");

                    b.Navigation("CertifyMst");

                    b.Navigation("GoldKrtMst");

                    b.Navigation("JewelTypeMst");

                    b.Navigation("ProdMst");

                    b.Navigation("StoneQltyMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.OrderMst", "OrderMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMst");

                    b.Navigation("OrderMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("OrderMsts")
                        .HasForeignKey("UserID");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", null)
                        .WithMany("StoneMsts")
                        .HasForeignKey("ItemMstStyle_Code");

                    b.HasOne("projectsem3_backend.Models.StoneQltyMst", "StoneQltyMst")
                        .WithMany("StoneMsts")
                        .HasForeignKey("StoneQlty_ID");

                    b.Navigation("StoneQltyMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Navigation("DimMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("DimMsts");

                    b.Navigation("OrderDetailMsts");

                    b.Navigation("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Navigation("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Navigation("ItemMsts");

                    b.Navigation("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("Inquiries");

                    b.Navigation("OrderMsts");
                });
#pragma warning restore 612, 618
        }
    }
}
