// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using projectsem3_backend.data;

#nullable disable

namespace projectsem3_backend.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240225160913_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("projectsem3_backend.Models.AdminLoginMst", b =>
                {
                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AdminEmail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("OnlineStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("UserName");

                    b.ToTable("AdminLoginMsts");

                    b.HasData(
                        new
                        {
                            UserName = "admin1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9021),
                            LastAccessTime = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9007),
                            OnlineStatus = false,
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9022)
                        },
                        new
                        {
                            UserName = "admin2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9025),
                            LastAccessTime = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9024),
                            OnlineStatus = false,
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 318, DateTimeKind.Local).AddTicks(9025)
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Property<string>("Brand_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Brand_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Brand_ID");

                    b.ToTable("BrandMsts");

                    b.HasData(
                        new
                        {
                            Brand_ID = "1",
                            Brand_Type = "Asmi",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(322),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(326),
                            Visible = true
                        },
                        new
                        {
                            Brand_ID = "2",
                            Brand_Type = "D’damas",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(329),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(329),
                            Visible = true
                        },
                        new
                        {
                            Brand_ID = "3",
                            Brand_Type = "ABC Jewelers",
                            Brand_Year = 1913,
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(331),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(332),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("ID");

                    b.HasIndex("Style_Code");

                    b.HasIndex("UserID");

                    b.ToTable("CartLists");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            MRP = 1000m,
                            Product_Name = "Product 1",
                            Quantity = 1,
                            Style_Code = "1",
                            UserID = "1"
                        },
                        new
                        {
                            ID = "2",
                            MRP = 2000m,
                            Product_Name = "Product 2",
                            Quantity = 1,
                            Style_Code = "2",
                            UserID = "2"
                        },
                        new
                        {
                            ID = "3",
                            MRP = 1500m,
                            Product_Name = "Product 3",
                            Quantity = 1,
                            Style_Code = "3",
                            UserID = "3"
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Property<string>("Cat_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Cat_ID");

                    b.ToTable("CatMsts");

                    b.HasData(
                        new
                        {
                            Cat_ID = "1",
                            Cat_Name = "Silver Jewelry",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(808),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(810),
                            Visible = true
                        },
                        new
                        {
                            Cat_ID = "2",
                            Cat_Name = "Gold Jewelry",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(812),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(812),
                            Visible = true
                        },
                        new
                        {
                            Cat_ID = "3",
                            Cat_Name = "Diamond Jewelry",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(814),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(815),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Property<string>("Certify_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Certify_ID");

                    b.ToTable("CertifyMsts");

                    b.HasData(
                        new
                        {
                            Certify_ID = "1",
                            Certify_Type = "BIS Hallmark",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3830),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3834),
                            Visible = true
                        },
                        new
                        {
                            Certify_ID = "2",
                            Certify_Type = "IGI",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3836),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3836),
                            Visible = true
                        },
                        new
                        {
                            Certify_ID = "3",
                            Certify_Type = "GIA",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3838),
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(3838),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Property<string>("DimID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimCrt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimImg")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimPrice")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimSubType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DimType")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DimYear")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimID");

                    b.ToTable("DimInfoMsts");

                    b.HasData(
                        new
                        {
                            DimID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7569),
                            DimCrt = "1",
                            DimImg = "",
                            DimPrice = "1000",
                            DimSubType = "Premium",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7571),
                            Visible = true
                        },
                        new
                        {
                            DimID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7574),
                            DimCrt = "2",
                            DimImg = "",
                            DimPrice = "2000",
                            DimSubType = "Standard",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7574),
                            Visible = true
                        },
                        new
                        {
                            DimID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7577),
                            DimCrt = "3",
                            DimImg = "",
                            DimPrice = "1500",
                            DimSubType = "Economy",
                            DimType = "Diamond",
                            DimYear = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7577),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.Property<string>("DimMst_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DimSubType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Dim_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Dim_Size")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimMst_ID");

                    b.HasIndex("DimID");

                    b.HasIndex("DimQlty_ID");

                    b.HasIndex("DimSubType_ID");

                    b.HasIndex("Style_Code")
                        .IsUnique()
                        .HasFilter("[Style_Code] IS NOT NULL");

                    b.ToTable("DimMsts");

                    b.HasData(
                        new
                        {
                            DimMst_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1032),
                            DimID = "1",
                            DimQlty_ID = "1",
                            DimSubType_ID = "1",
                            Dim_Amt = 1000m,
                            Dim_Crt = 1m,
                            Dim_Gm = 1m,
                            Dim_Pcs = 1m,
                            Dim_Rate = 1000m,
                            Dim_Size = 1m,
                            Style_Code = "1",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1036),
                            Visible = true
                        },
                        new
                        {
                            DimMst_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1042),
                            DimID = "2",
                            DimQlty_ID = "2",
                            DimSubType_ID = "2",
                            Dim_Amt = 2000m,
                            Dim_Crt = 2m,
                            Dim_Gm = 2m,
                            Dim_Pcs = 2m,
                            Dim_Rate = 2000m,
                            Dim_Size = 2m,
                            Style_Code = "2",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1043),
                            Visible = true
                        },
                        new
                        {
                            DimMst_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1047),
                            DimID = "3",
                            DimQlty_ID = "3",
                            DimSubType_ID = "3",
                            Dim_Amt = 1500m,
                            Dim_Crt = 3m,
                            Dim_Gm = 3m,
                            Dim_Pcs = 3m,
                            Dim_Rate = 1500m,
                            Dim_Size = 3m,
                            Style_Code = "3",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(1048),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Property<string>("DimQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimQlty_ID");

                    b.ToTable("DimQltyMsts");

                    b.HasData(
                        new
                        {
                            DimQlty_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3220),
                            DimQlty = "AD",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3224),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3226),
                            DimQlty = "VS",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3227),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3228),
                            DimQlty = "SI",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3229),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3230),
                            DimQlty = "FD",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3231),
                            Visible = true
                        },
                        new
                        {
                            DimQlty_ID = "5",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3232),
                            DimQlty = "WS",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(3233),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Property<string>("DimSubType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DimQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("DimSubType_ID");

                    b.ToTable("DimQltySubMsts");

                    b.HasData(
                        new
                        {
                            DimSubType_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7011),
                            DimQlty = "Premium",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7015),
                            Visible = true
                        },
                        new
                        {
                            DimSubType_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7017),
                            DimQlty = "Standard",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7018),
                            Visible = true
                        },
                        new
                        {
                            DimSubType_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7019),
                            DimQlty = "Economy",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 336, DateTimeKind.Local).AddTicks(7020),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Property<string>("GoldType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Gold_Crt")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gold_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("GoldType_ID");

                    b.ToTable("GoldKrtMsts");

                    b.HasData(
                        new
                        {
                            GoldType_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6663),
                            Gold_Crt = "18K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6666),
                            Visible = true
                        },
                        new
                        {
                            GoldType_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6669),
                            Gold_Crt = "22K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6670),
                            Visible = true
                        },
                        new
                        {
                            GoldType_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6672),
                            Gold_Crt = "24K",
                            Gold_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(6672),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.Property<string>("ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("Cdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Comment")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Contact")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Reply")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("ID");

                    b.HasIndex("UserID");

                    b.ToTable("Inquiries");

                    b.HasData(
                        new
                        {
                            ID = "1",
                            Cdate = new DateTime(2024, 2, 25, 23, 9, 13, 319, DateTimeKind.Local).AddTicks(2352),
                            City = "HCM",
                            Comment = "Test 1",
                            Contact = "0123456789",
                            EmailID = "user1@gmail.com",
                            Name = "User 1",
                            Reply = "Reply 1",
                            UserID = "1",
                            Visible = true
                        },
                        new
                        {
                            ID = "2",
                            Cdate = new DateTime(2024, 2, 25, 23, 9, 13, 319, DateTimeKind.Local).AddTicks(2358),
                            City = "HCM",
                            Comment = "Test 2",
                            Contact = "0987654321",
                            EmailID = "user2@gmail.com",
                            Name = "User 2",
                            Reply = "Reply 2",
                            UserID = "2",
                            Visible = true
                        },
                        new
                        {
                            ID = "3",
                            Cdate = new DateTime(2024, 2, 25, 23, 9, 13, 319, DateTimeKind.Local).AddTicks(2363),
                            City = "HCM",
                            Comment = "Test 3",
                            Contact = "0135792468",
                            EmailID = "user3@gmail.com",
                            Name = "User 3",
                            Reply = "Reply 3",
                            UserID = "3",
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Brand_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Cat_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Certify_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("GoldType_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Gold_Amt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Rate")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Gold_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Jewellery_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Net_Gold")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Other_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Pairs")
                        .HasColumnType("int");

                    b.Property<string>("Prod_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Prod_Quality")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Stone_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Stone_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Tot_Gross_Wt")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Tot_Making")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("Visible")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Wstg")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<decimal?>("Wstg_Per")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("Style_Code");

                    b.HasIndex("Brand_ID");

                    b.HasIndex("Cat_ID");

                    b.HasIndex("Certify_ID");

                    b.HasIndex("GoldType_ID");

                    b.HasIndex("Jewellery_ID");

                    b.HasIndex("Prod_ID");

                    b.HasIndex("StoneQlty_ID");

                    b.ToTable("ItemMsts");

                    b.HasData(
                        new
                        {
                            Style_Code = "1",
                            Brand_ID = "1",
                            Cat_ID = "1",
                            Certify_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8644),
                            GoldType_ID = "1",
                            Gold_Amt = 1000m,
                            Gold_Making = 1000m,
                            Gold_Rate = 1000m,
                            Gold_Wt = 1m,
                            ImagePath = "https://sjc.com.vn/upload/35-nutg0004_1475050374.jpg",
                            Jewellery_ID = "1",
                            MRP = 1000m,
                            Net_Gold = 1m,
                            Other_Making = 1000m,
                            Pairs = 1,
                            Prod_ID = "1",
                            Prod_Quality = "Premium",
                            Product_Name = "Product 1",
                            Quantity = 100,
                            StoneQlty_ID = "1",
                            Stone_Making = 1000m,
                            Stone_Wt = 1m,
                            Tot_Gross_Wt = 1m,
                            Tot_Making = 1000m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8656),
                            Visible = true,
                            Wstg = 1m,
                            Wstg_Per = 1m
                        },
                        new
                        {
                            Style_Code = "2",
                            Brand_ID = "2",
                            Cat_ID = "2",
                            Certify_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8667),
                            GoldType_ID = "2",
                            Gold_Amt = 2000m,
                            Gold_Making = 2000m,
                            Gold_Rate = 2000m,
                            Gold_Wt = 2m,
                            ImagePath = "https://sjc.com.vn/upload/28-ltdc0096_1475054675.jpg",
                            Jewellery_ID = "2",
                            MRP = 2000m,
                            Net_Gold = 2m,
                            Other_Making = 2000m,
                            Pairs = 2,
                            Prod_ID = "2",
                            Prod_Quality = "Standard",
                            Product_Name = "Product 2",
                            Quantity = 100,
                            StoneQlty_ID = "2",
                            Stone_Making = 2000m,
                            Stone_Wt = 2m,
                            Tot_Gross_Wt = 2m,
                            Tot_Making = 2000m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8668),
                            Visible = true,
                            Wstg = 2m,
                            Wstg_Per = 2m
                        },
                        new
                        {
                            Style_Code = "3",
                            Brand_ID = "3",
                            Cat_ID = "3",
                            Certify_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8676),
                            GoldType_ID = "3",
                            Gold_Amt = 1500m,
                            Gold_Making = 1500m,
                            Gold_Rate = 1500m,
                            Gold_Wt = 3m,
                            ImagePath = "",
                            Jewellery_ID = "3",
                            MRP = 1500m,
                            Net_Gold = 3m,
                            Other_Making = 1500m,
                            Pairs = 3,
                            Prod_ID = "3",
                            Prod_Quality = "Economy",
                            Product_Name = "Product 3",
                            Quantity = 100,
                            StoneQlty_ID = "3",
                            Stone_Making = 1500m,
                            Stone_Wt = 3m,
                            Tot_Gross_Wt = 3m,
                            Tot_Making = 1500m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 334, DateTimeKind.Local).AddTicks(8676),
                            Visible = true,
                            Wstg = 3m,
                            Wstg_Per = 3m
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Property<string>("Jewellery_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Jewellery_Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Jewellery_ID");

                    b.ToTable("JewelTypeMsts");

                    b.HasData(
                        new
                        {
                            Jewellery_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9899),
                            Jewellery_Type = "Ring",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9901),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9903),
                            Jewellery_Type = "Earring",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9903),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9905),
                            Jewellery_Type = "Necklace",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9906),
                            Visible = true
                        },
                        new
                        {
                            Jewellery_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9907),
                            Jewellery_Type = "Bracelet",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9907),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("MRP")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("Product_Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Order_ID", "Style_Code");

                    b.HasIndex("Style_Code");

                    b.ToTable("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Property<string>("Order_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("OrderDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("OrderStatus")
                        .HasColumnType("int");

                    b.Property<string>("Order_Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Order_Note")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.Property<string>("cancelreason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("creditCardNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("cvv")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("orderInfo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("orderPayment")
                        .HasColumnType("int");

                    b.Property<string>("order_MobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("paymenturl")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Order_ID");

                    b.HasIndex("UserID");

                    b.ToTable("OrderMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Property<string>("Prod_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Prod_Type")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Prod_ID");

                    b.ToTable("ProdMsts");

                    b.HasData(
                        new
                        {
                            Prod_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9411),
                            Prod_Type = "Gold Ring",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9415),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9417),
                            Prod_Type = "Diamond Earring",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9418),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9419),
                            Prod_Type = "Silver Necklace",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9420),
                            Visible = true
                        },
                        new
                        {
                            Prod_ID = "4",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9422),
                            Prod_Type = "Silver Ring",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 337, DateTimeKind.Local).AddTicks(9422),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.Property<string>("Stone_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ItemMstStyle_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<decimal?>("Stone_Amt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Crt")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Gm")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Pcs")
                        .HasColumnType("decimal(10,2)");

                    b.Property<decimal?>("Stone_Rate")
                        .HasColumnType("decimal(10,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("Stone_ID");

                    b.HasIndex("ItemMstStyle_Code");

                    b.HasIndex("StoneQlty_ID");

                    b.ToTable("StoneMsts");

                    b.HasData(
                        new
                        {
                            Stone_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(94),
                            StoneQlty_ID = "1",
                            Stone_Amt = 1000m,
                            Stone_Crt = 1m,
                            Stone_Gm = 1m,
                            Stone_Pcs = 1m,
                            Stone_Rate = 1000m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(104)
                        },
                        new
                        {
                            Stone_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(110),
                            StoneQlty_ID = "2",
                            Stone_Amt = 2000m,
                            Stone_Crt = 2m,
                            Stone_Gm = 2m,
                            Stone_Pcs = 2m,
                            Stone_Rate = 2000m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(111)
                        },
                        new
                        {
                            Stone_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(115),
                            StoneQlty_ID = "3",
                            Stone_Amt = 1500m,
                            Stone_Crt = 3m,
                            Stone_Gm = 3m,
                            Stone_Pcs = 3m,
                            Stone_Rate = 1500m,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 324, DateTimeKind.Local).AddTicks(116)
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Property<string>("StoneQlty_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("StoneQlty")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Stone_Year")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool?>("Visible")
                        .HasColumnType("bit");

                    b.HasKey("StoneQlty_ID");

                    b.ToTable("StoneQltyMsts");

                    b.HasData(
                        new
                        {
                            StoneQlty_ID = "1",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4565),
                            StoneQlty = "Ruby",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4577),
                            Visible = true
                        },
                        new
                        {
                            StoneQlty_ID = "2",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4580),
                            StoneQlty = "Meena",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4581),
                            Visible = true
                        },
                        new
                        {
                            StoneQlty_ID = "3",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4583),
                            StoneQlty = "Sapphire",
                            Stone_Year = 1913,
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 325, DateTimeKind.Local).AddTicks(4584),
                            Visible = true
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<bool?>("Activate")
                        .HasColumnType("bit");

                    b.Property<string>("Address")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("City")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DOB")
                        .HasColumnType("datetime2");

                    b.Property<string>("EmailID")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("IsVerified")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("LastAccessTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("MobNo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("OnlineStatus")
                        .HasColumnType("bit");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserFname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserLname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserID");

                    b.ToTable("UserRegMsts");

                    b.HasData(
                        new
                        {
                            UserID = "1",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9769),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9773),
                            DOB = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9748),
                            EmailID = "user1@gmail.com",
                            IsVerified = true,
                            LastAccessTime = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9772),
                            MobNo = "0123456789",
                            OnlineStatus = false,
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9774),
                            UserFname = "User",
                            UserLname = "1",
                            UserName = "user1"
                        },
                        new
                        {
                            UserID = "2",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9783),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9786),
                            DOB = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9782),
                            EmailID = "user2@gmail.com",
                            IsVerified = true,
                            LastAccessTime = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9785),
                            MobNo = "0123456789",
                            OnlineStatus = false,
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9787),
                            UserFname = "User",
                            UserLname = "2",
                            UserName = "user2"
                        },
                        new
                        {
                            UserID = "3",
                            Activate = true,
                            Address = "HCM",
                            CDate = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9790),
                            City = "HCM",
                            CreatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9793),
                            DOB = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9789),
                            EmailID = "user3@gmail.com",
                            IsVerified = true,
                            LastAccessTime = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9792),
                            MobNo = "0123456789",
                            OnlineStatus = false,
                            Password = "$2a$12$36eo6oF9uDI0Yf3HJqOsgu6yAkQXceqjPw7WPD1Sb3S/rC4nfKnDu",
                            State = "HCM",
                            UpdatedAt = new DateTime(2024, 2, 25, 23, 9, 13, 320, DateTimeKind.Local).AddTicks(9794),
                            UserFname = "User",
                            UserLname = "3",
                            UserName = "user3"
                        });
                });

            modelBuilder.Entity("projectsem3_backend.Models.Wishlist", b =>
                {
                    b.Property<string>("WhistList_ID")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Style_Code")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("UserID")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("WhistList_ID");

                    b.HasIndex("Style_Code");

                    b.HasIndex("UserID");

                    b.ToTable("Wishlists");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CartList", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("CartLists")
                        .HasForeignKey("Style_Code");

                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("CartLists")
                        .HasForeignKey("UserID");

                    b.Navigation("ItemMst");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.DimInfoMst", "DimInfoMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimID");

                    b.HasOne("projectsem3_backend.Models.DimQltyMst", "DimQltyMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimQlty_ID");

                    b.HasOne("projectsem3_backend.Models.DimQltySubMst", "DimQltySubMst")
                        .WithMany("DimMsts")
                        .HasForeignKey("DimSubType_ID");

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithOne("DimMsts")
                        .HasForeignKey("projectsem3_backend.Models.DimMst", "Style_Code");

                    b.Navigation("DimInfoMst");

                    b.Navigation("DimQltyMst");

                    b.Navigation("DimQltySubMst");

                    b.Navigation("ItemMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.Inquiry", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("Inquiries")
                        .HasForeignKey("UserID");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.BrandMst", "BrandMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Brand_ID");

                    b.HasOne("projectsem3_backend.Models.CatMst", "CatMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Cat_ID");

                    b.HasOne("projectsem3_backend.Models.CertifyMst", "CertifyMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Certify_ID");

                    b.HasOne("projectsem3_backend.Models.GoldKrtMst", "GoldKrtMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("GoldType_ID");

                    b.HasOne("projectsem3_backend.Models.JewelTypeMst", "JewelTypeMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Jewellery_ID");

                    b.HasOne("projectsem3_backend.Models.ProdMst", "ProdMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("Prod_ID");

                    b.HasOne("projectsem3_backend.Models.StoneQltyMst", "StoneQltyMst")
                        .WithMany("ItemMsts")
                        .HasForeignKey("StoneQlty_ID");

                    b.Navigation("BrandMst");

                    b.Navigation("CatMst");

                    b.Navigation("CertifyMst");

                    b.Navigation("GoldKrtMst");

                    b.Navigation("JewelTypeMst");

                    b.Navigation("ProdMst");

                    b.Navigation("StoneQltyMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderDetailMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.OrderMst", "OrderMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Order_ID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("OrderDetailMsts")
                        .HasForeignKey("Style_Code")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ItemMst");

                    b.Navigation("OrderMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("OrderMsts")
                        .HasForeignKey("UserID");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneMst", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", null)
                        .WithMany("StoneMsts")
                        .HasForeignKey("ItemMstStyle_Code");

                    b.HasOne("projectsem3_backend.Models.StoneQltyMst", "StoneQltyMst")
                        .WithMany("StoneMsts")
                        .HasForeignKey("StoneQlty_ID");

                    b.Navigation("StoneQltyMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.Wishlist", b =>
                {
                    b.HasOne("projectsem3_backend.Models.ItemMst", "ItemMst")
                        .WithMany("Wishlists")
                        .HasForeignKey("Style_Code");

                    b.HasOne("projectsem3_backend.Models.UserRegMst", "UserRegMst")
                        .WithMany("Wishlists")
                        .HasForeignKey("UserID");

                    b.Navigation("ItemMst");

                    b.Navigation("UserRegMst");
                });

            modelBuilder.Entity("projectsem3_backend.Models.BrandMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CatMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.CertifyMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimInfoMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltyMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.DimQltySubMst", b =>
                {
                    b.Navigation("DimMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.GoldKrtMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ItemMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("DimMsts");

                    b.Navigation("OrderDetailMsts");

                    b.Navigation("StoneMsts");

                    b.Navigation("Wishlists");
                });

            modelBuilder.Entity("projectsem3_backend.Models.JewelTypeMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.OrderMst", b =>
                {
                    b.Navigation("OrderDetailMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.ProdMst", b =>
                {
                    b.Navigation("ItemMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.StoneQltyMst", b =>
                {
                    b.Navigation("ItemMsts");

                    b.Navigation("StoneMsts");
                });

            modelBuilder.Entity("projectsem3_backend.Models.UserRegMst", b =>
                {
                    b.Navigation("CartLists");

                    b.Navigation("Inquiries");

                    b.Navigation("OrderMsts");

                    b.Navigation("Wishlists");
                });
#pragma warning restore 612, 618
        }
    }
}
